### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by johnnygiter** [Red5d/docker-autocompose#22]
Did exactly as instuction says, Ubuntu 20
```
/autocmp/docker-autocompose# docker run --rm -v /var/run/docker.sock:/var/run/docker.sock red5d/docker-autocompose Test
Traceback (most recent call last):
  File "/usr/src/app/./autocompose.py", line 3, in <module>
    import sys, argparse, pyaml, docker
  File "/usr/local/lib/python3.9/site-packages/docker-5.0.0-py3.9.egg/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/usr/local/lib/python3.9/site-packages/docker-5.0.0-py3.9.egg/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/usr/local/lib/python3.9/site-packages/docker-5.0.0-py3.9.egg/docker/api/client.py", line 10, in <module>
    from .. import auth
  File "/usr/local/lib/python3.9/site-packages/docker-5.0.0-py3.9.egg/docker/auth.py", line 5, in <module>
    import six
ModuleNotFoundError: No module named 'six'
```

**Comment by Red5d** [comment]
That's weird. I just tested myself and ran that exact command and it worked. Make sure you have the latest docker image with:
`docker pull red5d/docker-autocompose`
and try running that again. Also, what version of docker are you running on the host system?

**Comment by Red5d** [comment]
Not sure if I had an old image or something, and I'm not sure why it wasn't needed before, but it does need the "six" module now. Merged a fix for it from @LunaticMuch now.

**Comment by johnnygiter** [comment]
Sorry for little delay, I pulled today latest version did exacrly the same on the same config and worked, so solved:)
Thank you
