### ISSUE TITLE
PermissionError: [Errno 1] Operation not permitted

### ISSUE THREAD

**Issue by raftersvk** [Red5d/docker-autocompose#26]
Hello,

I am trying to use your script to compose an existing ocntainer, but I get the following error :
pi@raspberrypi:~ $ sudo docker run --rm -v /var/run/docker.sock:/var/run/docker.sock ghcr.io/red5d/docker-autocompose 4b3cc393a269
Fatal Python error: init_interp_main: can't initialize time
Python runtime state: core initialized
PermissionError: [Errno 1] Operation not permitted

Current thread 0xb6f4e390 (most recent call first):
<no Python frame>

do you have any idea what could be the issue here ?

**Comment by Velkas** [comment]
Getting the same error with latest image.

```
sudo docker run --rm -v /var/run/docker.sock:/var/run/docker.sock ghcr.io/red5d/docker-autocompose <container1> <container2> <container3> <container4> <container5>
Traceback (most recent call last):
  File "/usr/src/app/./autocompose.py", line 3, in <module>
    import sys, argparse, pyaml, docker
  File "/usr/local/lib/python3.10/site-packages/docker-5.0.3-py3.10.egg/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/usr/local/lib/python3.10/site-packages/docker-5.0.3-py3.10.egg/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/usr/local/lib/python3.10/site-packages/docker-5.0.3-py3.10.egg/docker/api/client.py", line 6, in <module>
    import requests
  File "/usr/local/lib/python3.10/site-packages/requests-2.26.0-py3.10.egg/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/usr/local/lib/python3.10/site-packages/urllib3-1.26.7-py3.10.egg/urllib3/__init__.py", line 7, in <module>
    import logging
  File "/usr/local/lib/python3.10/logging/__init__.py", line 57, in <module>
    _startTime = time.time()
PermissionError: [Errno 1] Operation not permitted
```

**Comment by raftersvk** [comment]
after updating my distribution it all works. thanks
