### ISSUE TITLE
Operation not permitted

### ISSUE THREAD

**Issue by Reporter1** [Red5d/docker-autocompose#40]
Hi

I'm trying to make / get a yml output for my container but im receiving the Operation not permitted error.

I'm using the docker container method, simply followed the instructions you wrote, pull the image and run the docker command and add the container id / name.

But im seeing the below? Any ideas? 

BTW im still learing so bare with me. 

Traceback (most recent call last):
  File "/usr/src/app/./autocompose.py", line 3, in <module>
    import sys, argparse, pyaml, docker
  File "/usr/local/lib/python3.10/site-packages/docker-5.0.3-py3.10.egg/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/usr/local/lib/python3.10/site-packages/docker-5.0.3-py3.10.egg/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/usr/local/lib/python3.10/site-packages/docker-5.0.3-py3.10.egg/docker/api/client.py", line 6, in <module>
    import requests
  File "/usr/local/lib/python3.10/site-packages/requests-2.28.1-py3.10.egg/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/usr/local/lib/python3.10/site-packages/urllib3-1.26.9-py3.10.egg/urllib3/__init__.py", line 7, in <module>
    import logging
  File "/usr/local/lib/python3.10/logging/__init__.py", line 57, in <module>
    _startTime = time.time()
PermissionError: [Errno 1] Operation not permitted

**Comment by Reporter1** [comment]
All sorted now, need to update libseccomp2.

Found the solution here https://github.com/Red5d/docker-autocompose/issues/26

UPDATE: Steps to update library on raspberry pi 3:

find the latest version here http://ftp.debian.org/debian/pool/main/libs/libseccomp/?C=M;O=D as the below version in the command is no longer available, replace the latest in the command and run the below..

wget http://ftp.us.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.5.1-1_armhf.deb


sudo dpkg -i libseccomp2_2.5.1-1_armhf.deb


https://community.home-assistant.io/t/migration-to-2021-7-fails-fatal-python-error-init-interp-main-cant-initialize-time/320648
