### ISSUE TITLE
RuntimeError: invalid GMT offset

### ISSUE THREAD

**Issue by Gitpaad** [Red5d/docker-autocompose#70]
Hi

I am trying to run the autocompose with the docker image. but somehow it comes to an error. does anyone have a hint?
********************************************************

docker run --rm -v /var/run/docker.sock:/var/run/docker.sock ghcr.io/red5d/docker-autocompose $(docker ps -aq)
Traceback (most recent call last):
  File "/usr/src/app/./autocompose.py", line 9, in <module>
    import docker
  File "/usr/local/lib/python3.12/site-packages/docker-7.0.0-py3.12.egg/docker/__init__.py", line 1, in <module>
    from .api import APIClient
  File "/usr/local/lib/python3.12/site-packages/docker-7.0.0-py3.12.egg/docker/api/__init__.py", line 1, in <module>
    from .client import APIClient
  File "/usr/local/lib/python3.12/site-packages/docker-7.0.0-py3.12.egg/docker/api/client.py", line 6, in <module>
    import requests
  File "/usr/local/lib/python3.12/site-packages/requests-2.31.0-py3.12.egg/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/usr/local/lib/python3.12/site-packages/urllib3-2.1.0-py3.12.egg/urllib3/__init__.py", line 8, in <module>
    import logging
  File "/usr/local/lib/python3.12/logging/__init__.py", line 26, in <module>
    import sys, os, time, io, re, traceback, warnings, weakref, collections.abc
RuntimeError: invalid GMT offset

**Comment by Gitpaad** [comment]
solved
