### ISSUE TITLE
unexpected keyword argument 'chunked'

### ISSUE THREAD

**Issue by nmcc1212** [Red5d/docker-autocompose#74]
Hi,
I installed through pipx, i get this error when running with and without sudo
```
sudo /home/nial/.local/bin/autocompose jenkins
Traceback (most recent call last):
  File "/home/nial/.local/bin/autocompose", line 8, in <module>
    sys.exit(main())
  File "/home/nial/.local/pipx/venvs/docker-autocompose/bin/autocompose.py", line 11, in main
    generate(args)
  File "/home/nial/.local/pipx/venvs/docker-autocompose/bin/autocompose.py", line 18, in generate
    cid = [x['Id'] for x in c.containers() if args.cname in x['Names'][0]][0]
  File "/home/nial/.local/pipx/venvs/docker-autocompose/lib/python3.10/site-packages/docker/api/container.py", line 85, in containers
    res = self._result(self._get(u, params=params), True)
  File "/home/nial/.local/pipx/venvs/docker-autocompose/lib/python3.10/site-packages/docker/utils/decorators.py", line 47, in inner
    return f(self, *args, **kwargs)
  File "/home/nial/.local/pipx/venvs/docker-autocompose/lib/python3.10/site-packages/docker/client.py", line 139, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/home/nial/.local/pipx/venvs/docker-autocompose/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/home/nial/.local/pipx/venvs/docker-autocompose/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/nial/.local/pipx/venvs/docker-autocompose/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/nial/.local/pipx/venvs/docker-autocompose/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/nial/.local/pipx/venvs/docker-autocompose/lib/python3.10/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/home/nial/.local/pipx/venvs/docker-autocompose/lib/python3.10/site-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
TypeError: HTTPConnection.request() got an unexpected keyword argument 'chunked'
```

**Comment by nmcc1212** [comment]
works when running normally (cloning repo and running python file)

**Comment by Red5d** [comment]
Running via installation from the repo or via the docker image are the current recommended ways to run this tool. The version on pip hasn't been updated in a while.

**Comment by nmcc1212** [comment]
Might be worth putting that in the readme, or removing it entirely
